name: CI

on:
  pull_request:
  push:
    branches:
      - test
  schedule:
    - cron: '0 1 * * *'

env:
  RUSTFLAGS: -D warnings
  RUST_BACKTRACE: 1

defaults:
  run:
    shell: bash

jobs:
  test:
    name: cargo +${{ matrix.rust }} test (${{ matrix.os }})
    strategy:
      matrix:
        rust:
          - nightly
        os:
         - ubuntu-latest
         - macos-latest
         - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        # --no-self-update is necessary because the windows environment cannot self-update rustup.exe.
        run: rustup update ${{ matrix.rust }} --no-self-update && rustup default ${{ matrix.rust }}
      - run: cargo test --workspace --all-features
      - run: cargo test --workspace --all-features --release

  docs:
    name: cargo doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update nightly && rustup default nightly
      - run: RUSTDOCFLAGS="-D warnings --cfg docsrs" cargo doc --workspace --no-deps --all-features
